name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Setup
        run: npm i -g pnpm@9

      - name: Install
        run: pnpm i

      - name: Lint
        run: pnpm run lint

  # test:
  #   runs-on: ${{ matrix.os }}

  #   strategy:
  #     matrix:
  #       node: [16.x, 18.x]
  #       os: [ubuntu-latest, windows-latest, macos-latest]
  #     fail-fast: false

  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Set node ${{ matrix.node }}
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ matrix.node }}

  #     - name: Setup
  #       run: npm i -g pnpm@8

  #     - name: Install
  #       run: pnpm i

  #     - name: Build
  #       run: pnpm run build

  #     - name: Test
  #       run: pnpm run test
